import Navbar from "./src/components/navbar";
import './globals.css';

export const metadata = {
  title: 'QrListo',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
